Fix the PhantomJS test error
- The tests for PR 73 were failing due to:

  ```
  $ sh spec/testrunner.sh
Serving HTTP on 0.0.0.0 port 8000 ...
TypeError: undefined is not an object (evaluating 'phantom.args.length')
  phantomjs://code/phantomjs-testrunner.js:2 in global code
  ```